// <auto-generated />
namespace LaTienda.Infraestructura.Datos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class NuevasEntidades_Producto_Marca_Rubro : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NuevasEntidades_Producto_Marca_Rubro));
        
        string IMigrationMetadata.Id
        {
            get { return "202202270057408_NuevasEntidades_Producto_Marca_Rubro"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
